### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create an HTML and CSS files.
- [x] Add a div[class = "container"]
- [x] Set the background color to green
- [x] Add image of the car
- [x] Make sure the car is facing east
- [x] Adjust the size of the car
