### ISSUE TITLE
 User can start their car 

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Create and object to hold x and y values
- [x] Give an absolute position for the image
- [x] Create a function that change the top and left offset when space is pushed
- [x] Adjust the function so that it happens every 16 milliseconds.
- [ ] Remove any unnecessary comment or console.log
